name: Contributors Report
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate changelog"]  # changelog-generator.yml의 name과 일치해야 함
    types:
      - completed

permissions:
  contents: read
  issues: write

jobs:
  contributor_report:
    name: contributor report
    runs-on: ubuntu-latest

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # 이전 달의 첫째 날
          start_date=$(date -d "last month" +%Y-%m-01)
          # 이전 달의 마지막 날
          end_date=$(date -d "$start_date +1 month -1 day" +%Y-%m-%d)
          
          echo "START_DATE=$start_date" >> "$GITHUB_ENV"
          echo "END_DATE=$end_date" >> "$GITHUB_ENV"

      - name: Run contributor action
        uses: github/contributors@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          START_DATE: ${{ env.START_DATE }}
          END_DATE: ${{ env.END_DATE }}
          REPOSITORY_LIST: "somaz94/compress-decompress"  # 콤마로 구분된 레포지토리 목록
          SPONSOR_INFO: "true"

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Monthly contributor report
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./contributors.md
          assignees: somaz94 