name: Update Contributors

on:
  workflow_run:
    workflows: ["Generate changelog"]  # changelog-generator.yml의 name과 일치해야 함
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate Contributors List
        run: |
          echo "# Contributors" > CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md
          echo "Thanks goes to these wonderful people:" >> CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md
          
          # 봇 계정 패턴 정의
          BOT_PATTERNS=(
            "bot"
            "Bot"
            "BOT"
            "actions"
            "github-actions"
            "dependabot"
            "renovate"
            "[bot]"
            "-bot"
            "github-actions[bot]"
            "dependabot[bot]"
            "renovate[bot]"
          )
          
          # 봇 패턴을 grep 패턴으로 변환
          BOT_GREP_PATTERN=$(IFS="|"; echo "${BOT_PATTERNS[*]}")
          
          # 기여자 정보를 임시 파일에 저장
          declare -A contributors
          
          echo "## Code Contributors" >> CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md
          
          # 커밋 로그에서 author와 committer 정보 수집
          while IFS="|" read -r name email; do
            if [[ ! "$name" =~ ($BOT_GREP_PATTERN) ]] && [[ -z "${contributors[$email]}" ]]; then
              contributors[$email]="$name"
              echo "- $name" >> CONTRIBUTORS.md
            fi
          done < <(git log --format='%aN|%aE%n%cN|%cE' | sort -u)
          
          echo "" >> CONTRIBUTORS.md
          echo "## Pull Request Contributors" >> CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md
          
          # PR 작성자 정보 수집
          while IFS="|" read -r name email; do
            if [[ ! "$name" =~ ($BOT_GREP_PATTERN) ]] && [[ -z "${contributors[$email]}" ]]; then
              contributors[$email]="$name"
              echo "- $name" >> CONTRIBUTORS.md
            fi
          done < <(git log --format='%aN|%aE' --merges --grep="Merge pull request" | sort -u)
          
          echo "" >> CONTRIBUTORS.md
          echo "## Reviewers" >> CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md
          
          # PR 리뷰어 정보 수집 (코멘트나 승인 이력이 있는 사람)
          while IFS="|" read -r name email; do
            if [[ ! "$name" =~ ($BOT_GREP_PATTERN) ]] && [[ -z "${contributors[$email]}" ]]; then
              contributors[$email]="$name"
              echo "- $name (Reviewer)" >> CONTRIBUTORS.md
            fi
          done < <(git log --format='%aN|%aE' --grep="Reviewed-by:" --grep="Approved-by:" | sort -u)
          
          # 중복 제거 및 정렬
          sort -u -o CONTRIBUTORS.md{,}
          
          # 결과 확인
          echo "Generated Contributors List:"
          cat CONTRIBUTORS.md

      - name: Create Pull Request
        uses: somaz94/go-git-commit-action@v1
        with:
          user_email: actions@github.com
          user_name: GitHub Actions
          create_pr: true
          auto_branch: true
          branch: main
          pr_branch: main
          pr_base: main
          pr_title: "docs: update contributors list"
          pr_labels: "documentation"
          pr_body: |
            ## Update Contributors List
            
            This PR automatically updates the contributors list.
            
            ### Changes
            - Updated CONTRIBUTORS.md with latest contributors
            - Added code contributors from git history
            - Added PR contributors and reviewers
            - Excluded bot accounts
            - Removed duplicates
          github_token: ${{ secrets.PAT_TOKEN }}
          skip_if_empty: true
          delete_source_branch: true
