name: Update CONTRIBUTORS.md
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Create release"]  # release.yml의 name과 일치해야 함
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  update_contributors:
    name: Update Contributors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get contributors
        run: |
          {
            echo "# Contributors"
            echo ""
            echo "Contributions are welcome! Please feel free to submit a Pull Request."
            echo ""
            echo "## Contributors List"
            echo ""
            echo "Thanks goes to these wonderful people:"
            echo ""
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/${{ github.repository }}/contributors" | \
            jq -r '.[] | select(.type != "Bot" and .login != "github-actions[bot]" and .login != "actions-user") | "- [@\(.login)](\(.html_url))"' | \
            sort
          } > CONTRIBUTORS.md

      - name: Create Pull Request
        uses: somaz94/go-git-commit-action@v1
        with:
          user_email: actions@github.com
          user_name: GitHub Actions
          create_pr: true
          auto_branch: true
          branch: main
          pr_branch: main
          pr_base: main
          pr_title: "docs: update CONTRIBUTORS.md"
          pr_body: |
            ## CONTRIBUTORS.md Update
            
            This PR updates the contributors list in CONTRIBUTORS.md
            
            ### Changes
            - Updated contributors list from GitHub API
            - Excluded bot accounts
            - Added profile links to contributors
          pr_labels: "documentation"
          github_token: ${{ secrets.PAT_TOKEN }}
          file_pattern: "CONTRIBUTORS.md" 
          delete_source_branch: true
          pr_closed: false