name: Update Contributors

on:
  workflow_run:
    workflows: ["Generate changelog"]  # changelog-generator.yml의 name과 일치해야 함
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate Contributors List
        run: |
          echo "# Contributors" > CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md
          echo "Thanks goes to these wonderful people:" >> CONTRIBUTORS.md
          echo "" >> CONTRIBUTORS.md
          
          # 임시 파일에 기여자 정보 저장
          declare -A contributors
          
          while read contributor; do
            name=$(echo "$contributor" | cut -d '<' -f1 | xargs)
            email=$(echo "$contributor" | grep -o '<[^>]*>' | tr -d '<>')
            
            # 이미 처리된 이메일인지 확인
            if [[ -z "${contributors[$email]}" ]]; then
              user_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                         "https://api.github.com/search/users?q=$email+in:email")
              
              username=$(echo "$user_info" | jq -r '.items[0].login // empty')
              if [ ! -z "$username" ]; then
                echo "- [@$username](https://github.com/$username)" >> CONTRIBUTORS.md
              else
                echo "- $name" >> CONTRIBUTORS.md
              fi
              
              # 처리된 이메일 기록
              contributors[$email]="1"
            fi
          done < <(git log --format='%aN <%aE>' | \
                  grep -v "bot\|Bot\|BOT\|actions\|github-actions\|dependabot\|renovate" | \
                  sort)

      - name: Create Pull Request
        uses: somaz94/go-git-commit-action@v1
        with:
          user_email: actions@github.com
          user_name: GitHub Actions
          create_pr: true
          auto_branch: true
          branch: main
          pr_branch: main
          pr_base: main
          pr_title: "docs: update contributors list"
          pr_labels: "documentation"
          pr_body: |
            ## Update Contributors List
            
            This PR automatically updates the contributors list.
            
            ### Changes
            - Updated CONTRIBUTORS.md with latest contributors
            - Excluded bot accounts and automated systems
            - Added GitHub profile links where available
          github_token: ${{ secrets.PAT_TOKEN }}
          skip_if_empty: true
